### PR TITLE
Add both minified and non-minified version to dist, and update Bower.…

### PR DESCRIPTION
**Pull request by mndewitt**
Getting started on #46, just adding non-min and min versions to dist and updating the naming convention.   Should the non-minified version be included in the dist script, or in another property?

### CODE REVIEW

**Comment by wbuchwalter** [comment]
Cool!
Ideally, it would be cleaner to split the scripts a little bit yea.
Something like:
```JavaScript
{
"build": "npm run build:lib && npm run build:min & npm run build:max",
"build:lib": "rm -rf lib && `npm bin`/babel src --out-dir lib",
"build:min": "./node_modules/.bin/webpack --optimize-minimize lib/index.js dist/ng-redux.min.js",
"build:max": "./node_modules/.bin/webpack lib/index.js dist/ng-redux.js"
}
```

What do you think?

**Comment by mndewitt** [comment]
Yeah, I like that approach - branch is updated.  You okay then with: `"dist": "npm run build"`

**Comment by wbuchwalter** [comment]
You can just remove `dist` at this point, it's no needed anymore.
Everything else looks good :+1:

**Comment by mndewitt** [comment]
Sweet, all set :)

**Comment by wbuchwalter** [comment]
Thx! :)

**Pull request merged**
