### PR TITLE
Bower accessibility for ng-redux

### PR DESCRIPTION
**Pull request by abelmokadem**
Two main things in this PR:

- The package can now be registered on bower using the following command:

`bower register ng-redux git@github.com:wbuchwalter/ng-redux.git`

- The package has been minified from close to over 60kb down to 20kb by removing lodash as one big dependency and breaking this down to only functions that are used.

The command for creating the bower dist is `npm run dist`.

Hope this suits you well.

### CODE REVIEW

**Comment by wbuchwalter** [comment]
Thx Ash, nice work!

**Comment by wbuchwalter** [comment]
Regiestered on bower.

**Comment by abelmokadem** [comment]
Thanks a lot! :+1: If there is any issue with the dist file I am available to work on it.

**Comment by abelmokadem** [comment]
I believe you should add a new tag v3.0.2 so that the changes are picked up by bower

**Comment by wbuchwalter** [comment]
[Tag v3.1.0](https://github.com/wbuchwalter/ng-redux/releases/tag/3.1.0) added.

**Comment by abelmokadem** [comment]
Thx!

**Pull request merged**
