### PR TITLE
Use Babel 6 in loose mode to build JS

### PR DESCRIPTION
**Pull request by lautis**
Using loose mode prevents disables referencing Symbol in built JS. While the loose mode could cause subtle bugs, it currently only affects one for-of loop. Requiring babel-polyfill for that would be wasteful.

### CODE REVIEW

**Comment by 17cupsofcoffee** [comment]
Seconding this (or at least, any solution that gets rid of Symbol from the build) - currently trying to load an ng-redux application in IE 11 is throwing errors because of Symbol being undefined, and loading the whole polyfill feels like a massive expense considering none of my own code requires it.

**Comment by wbuchwalter** [comment]
@lautis :+1: Thanks, nice catch!
I will try to release that ASAP.

**Comment by wbuchwalter** [comment]
Released under `3.3.0`.
Thanks

**Comment by 17cupsofcoffee** [comment]
Thanks to both of you! :+1:

**Comment by sstorie** [comment]
Thanks for fixing this. I updated some packages last week and IE11 started choking with this error. I was a bit puzzled about where it was coming from, but this fix took care of it.

**Comment by wbuchwalter** [comment]
Glad it helped! :)

**Pull request merged**
