### PR TITLE
Fix typings in packaged index.d.ts

### LINKED ISSUE #44: index.d.ts in base folder is causing issue with TypeScript
I installed latest ```ng-redux``` module and put it into my project using browserify + tsify (I'm using TypeScript). I've also included the type definitions from the DT repo.

When I include this lib in my project via ```import 'ng-redux'```, I get the following error:

```
Error TS2306: File `node_modules/ng-redux/index.d.ts` is not a module
```

If I move ```index.d.ts``` outside the folder, it will compile properly and include the lib in my project.

Is it possible to move this file into ```dist``` folder or another location?

BTW thanks for making this lib, it's very helpful when using redux with ng1!

### PR DESCRIPTION
**Pull request by dballance**
Convert typescript typings to an external module.

Resolves #44

### CODE REVIEW

**Comment by wbuchwalter** [comment]
Hey Drew,
Thanks for the PR, looks good except one thing:

```Javascript
export var ngRedux: string;
export default ngRedux; 
```

Here you are just exporting a plain old string as default value. So this is probably not what you wanted to do.

Before we had:

```Javascript
declare module "ngRedux" {		
   export = ngRedux;		
}
```

this was the old internal module syntax, and it allowed you yo directly access all the interfaces like so:
```Javascript
var myVar: ngRedux.Middleware;
```

With the new external module syntax, the equivalent would be:

```Javascript
import * as ngRedux from 'ng-redux';
```

So you can remove the two last lines.
Thanks.

**Comment by dballance** [comment]
That's an intentional export to match what is exported from the module and to allow direct address of the angular module string.

With the current structure of index.d.ts in this pull request, you can address ng-redux as below. 

```typescript
import * as ngRedux from 'ng-redux';
import { rootReducer } from "./reducers/index";

angular.module('app', [ngRedux.default])
.config(($ngReduxProvider: ngRedux.INgReduxProvider) => {
    $ngReduxProvider.createStoreWith(rootReducer);
  });
```

The default export closely matches what is exported by the module and allows direct address of the interfaces. I used this pattern in a sample I was building (mostly to learn redux myself) and the above pattern worked for me.

Can see this sample [here](https://github.com/dballance/ts-ng-redux-counter-example/blob/master/app.ts) and it matches up to the PR mention in #44 with [redux-ui-router](https://github.com/neilff/redux-ui-router/pull/30/files). Does this achieve what you wanted?

**Comment by wbuchwalter** [comment]
:+1: 
Didn't thought about that, you're right.
Thanks!

**Comment by dballance** [comment]
:+1: 

Glad I could help!

**Comment by wbuchwalter** [comment]
I won't be able to release the npm package today, so will do that tomorrow. Sorry for the delay!

**Comment by mjw56** [comment]
awesome, thank you @dballance && @wbuchwalter! :+1:

**Pull request merged**
